### PR TITLE
Update Capabilities.md

### PR DESCRIPTION
**Pull request by 1nf0rmagician**
Fix grammar and links

### CODE REVIEW

**Comment by 1nf0rmagician** [comment]
The file mentions AssembleCapabilities which I can not find in the repo, so please let me know if the paragraph is still up to date or should be removed entirely.

**Comment by Toxantron** [comment]
I am sorry, there was a misunderstanding. xref is only replaced with relative paths for other Markdown documents. For namespaces and class references we keep xref.

**Comment by Toxantron** [comment]
> The file mentions AssembleCapabilities which I can not find in the repo, so please let me know if the paragraph is still up to date or should be removed entirely.

Good catch, AssembleCapabilities are no longer part of the AL

**Comment by dbeuchler** [comment]
> I am sorry, there was a misunderstanding. xref is only replaced with relative paths for other Markdown documents. For namespaces and class references we keep xref.

This was already discussed with @1nf0rmagician. He will change it and I squash this to dev.

**Comment by dbeuchler** [comment]
Thanks for changing api references back to xref like described in https://github.com/PHOENIXCONTACT/MORYX-Platform/issues/26 - Thanks also for the general contribution!

**Pull request merged**
