### PR TITLE
bugfix/78 - harmonized the namespaces

### PR DESCRIPTION
**Pull request by milmilkat**
changed namespaces based on folders structure

### CODE REVIEW

**Comment by Toxantron** [comment]
Thank you for taking the time to resolve this issue. There is a merge conflict that would need to be resolved, than I could merge this into `future` as namespace changes are only possible in the next major.

**Comment by milmilkat** [comment]
@Toxantron Sorry it took a long time to get back again. Now I got a good chance to take a look at it. As I branched it out of dev, if I make a PR to future, the changes look a lot more than what should be and not necessarily mine. In case that this PR will go into future branch, it could be better that a PR from dev to future would be made prior this PR. Then my changes would be more clear. If any changes are needed from my side, please let me know.

**Comment by Toxantron** [comment]
Thank you, I will take care of updating future prior to merging.

**Review by Toxantron — APPROVED** [review]

**Comment by Toxantron** [comment]
With all the recent changes to future, I don't think this applies anymore. Thanks anyway.

**Pull request closed without merging**
